CREATE OR REPLACE STORAGE INTEGRATION Azure_DL
    TYPE = EXTERNAL_STAGE
    STORAGE_PROVIDER = AZURE
    ENABLED = TRUE
    AZURE_TENANT_ID = 'a8eec281-aaa3-4dae-ac9b-9a398b9215e7'
    STORAGE_ALLOWED_LOCATIONS = ('azure://01datalaketesting.blob.core.windows.net/data-1/')

DESC INTEGRATION Azure_DL

CREATE OR REPLACE FILE FORMAT MANAGE_DB.FILE_FORMATS.AzureCSV
    TYPE = CSV
    FIELD_DELIMITER = ','
    SKIP_HEADER = 0
    NULL_IF = ('NULL', 'null', 'Null')
    EMPTY_FIELD_AS_NULL = TRUE

ALTER FILE FORMAT MANAGE_DB.FILE_FORMATS.AzureCSV SET SKIP_HEADER = 1;

CREATE OR REPLACE STAGE MANAGE_DB.EXTERNAL_STAGES.AzureSI_CSV
    URL = 'azure://01datalaketesting.blob.core.windows.net/data-1/ActivityLog-01.csv'
    FILE_FORMAT = MANAGE_DB.FILE_FORMATS.AzureCSV
    STORAGE_INTEGRATION = Azure_DL

LIST @MANAGE_DB.EXTERNAL_STAGES.AzureSI_CSV


CREATE OR REPLACE TABLE MANAGE_DB.PUBLIC.ActLog_1_CSV
AS
SELECT
    $1 AS COLUMN_1,
    $2 AS COLUMN_2,
    $3 AS COLUMN_3,
    $4 AS COLUMN_4,
    $5 AS COLUMN_5,
    $6 AS COLUMN_6,
    $7 AS COLUMN_7,
    $8 AS COLUMN_8,
    $9 AS COLUMN_9,
    $10 AS COLUMN_10,
    $11 AS COLUMN_11
FROM @MANAGE_DB.EXTERNAL_STAGES.AzureSI_CSV;


SELECT * FROM MANAGE_DB.PUBLIC.ActLog_1_CSV