USE ROLE SYSADMIN

CREATE OR REPLACE WAREHOUSE EXERCISE_WH
WAREHOUSE_TYPE = STANDARD --'SNOWPARK-OPTIMIZED'
WAREHOUSE_SIZE = XSMALL --'XS(1 credit) | S(2 credits) | M(4 credits) | L(8 credits) | XL(16 credits) ...'
SCALING_POLICY = 'Economy' --'Standard'
MIN_CLUSTER_COUNT = 1
MAX_CLUSTER_COUNT = 3
AUTO_SUSPEND = 600  -- automatically suspend the virtual warehouse after 10 minutes of not being used
AUTO_RESUME = TRUE 
INITIALLY_SUSPENDED = FALSE
COMMENT = 'This is a virtual warehouse of size X-SMALL that can be used to process queries.';
-- RESOURCE_MONITOR = <monitor_name>
-- ENABLE_QUERY_ACCELERATION = { TRUE | FALSE }
-- QUERY_ACCELERATION_MAX_SCALE_FACTOR = <num>

ALTER WAREHOUSE EXERCISE_WH SUSPEND
ALTER WAREHOUSE EXERCISE_WH RESUME
ALTER WAREHOUSE EXERCISE_WH ABORT ALL QUERIES
ALTER WAREHOUSE EXERCISE_WH RENAME TO TRIAL_01

ALTER WAREHOUSE TRIAL_01 SET 
AUTO_SUSPEND = 300
SCALING_POLICY = 'Standard'

DROP WAREHOUSE TRIAL_01

CREATE OR REPLACE WAREHOUSE WAREHOUSE_01
WAREHOUSE_TYPE = STANDARD 
WAREHOUSE_SIZE = XSMALL 
SCALING_POLICY = 'Standard' 
MIN_CLUSTER_COUNT = 1
MAX_CLUSTER_COUNT = 3
AUTO_SUSPEND = 300  
AUTO_RESUME = TRUE 
INITIALLY_SUSPENDED = FALSE
COMMENT = 'This is a virtual warehouse of size X-SMALL that can be used to process queries.';

ALTER WAREHOUSE WAREHOUSE_01 RESUME

USE WAREHOUSE WAREHOUSE_01



