// ** NECESSARY FOR ALL ** //
USE ROLE ACCOUNTADMIN;


--************************************** <UP> **************************************--


// BU1 - ROLE // CREATE ROLE AND GRANT USAGE TO WAREHOUSE FOR DATA ANALYSTS
CREATE ROLE DATA_ANALYST;
GRANT USAGE ON WAREHOUSE SnowProject_DA TO ROLE DATA_ANALYST;


// BU2 - USER // CREATE 2 USERS WITH CREDENTIALS AND GRANT ROLE TO USER
CREATE USER DA1 PASSWORD = 'DA1' LOGIN_NAME = 'DA1' DEFAULT_ROLE = 'DATA_ANALYST' DEFAULT_WAREHOUSE = 'SnowProject_DA'
    MUST_CHANGE_PASSWORD = FALSE;
CREATE USER DA2 PASSWORD = 'DA2' LOGIN_NAME = 'DA2' DEFAULT_ROLE = 'DATA_ANALYST' DEFAULT_WAREHOUSE = 'SnowProject_DA'
    MUST_CHANGE_PASSWORD = FALSE;
CREATE USER Tejas_Raut PASSWORD = 'TRR' LOGIN_NAME = 'TRR' DEFAULT_ROLE = 'DATA_ANALYST' DEFAULT_WAREHOUSE = 'SnowProject_DA'
    MUST_CHANGE_PASSWORD = FALSE;

GRANT ROLE DATA_ANALYST TO USER DA1;
GRANT ROLE DATA_ANALYST TO USER DA2;
GRANT ROLE DATA_ANALYST TO USER Tejas_Raut;


// BU3 - GRANT DATABASE & SCHEMA ACCESS // GRANT USAGE ON DATABASE AND SCHEMA TO SPECIFIC ROLES
GRANT USAGE ON DATABASE DATA_ANALYST_PROCESSED TO ROLE DATA_ANALYST;
GRANT USAGE ON SCHEMA DATA_ANALYST_PROCESSED.ETFS TO ROLE DATA_ANALYST;


// BU4 - GRANT TABLES ACCESS // GRANT USAGE ON TABLES TO SPECIFIC ROLES
GRANT SELECT ON ALL TABLES IN SCHEMA DATA_ANALYST_PROCESSED.ETFS TO ROLE DATA_ANALYST;


// BU5 - GRANT CRUD ACCESS // GRANT CRUD OPERATIONS ON TABLES TO SPECIFIC ROLES
GRANT INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA DATA_ANALYST_PROCESSED.ETFS TO ROLE DATA_ANALYST;


// BU6 - SHOW GRANTS //

SHOW GRANTS TO USER DA1; -- Check roles assigned to the user
SHOW GRANTS TO ROLE DATA_ANALYST; -- Check grants to the role


// BU7 - SHOW GRANTS //

GRANT OWNERSHIP ON STREAM DATA_WAREHOUSING_ANALYSTS.EXTERNAL_TABLES.ETF_PRICES_STREAM TO ROLE ACCOUNTADMIN;
GRANT SELECT ON STREAM DATA_WAREHOUSING_ANALYSTS.EXTERNAL_TABLES.ETF_PRICES_STREAM TO ROLE ACCOUNTADMIN;
GRANT REFERENCES ON STREAM DATA_WAREHOUSING_ANALYSTS.EXTERNAL_TABLES.ETF_PRICES_STREAM TO ROLE ACCOUNTADMIN;


--************************************** <DOWN> **************************************--


// BD1 - DROP (ROLE | USER) //

-- DROP ROLE DATA_ANALYST;
-- DROP USER DA1;
-- DROP USER DA2;


// BD2 - REVOKE (PRIVILAGES | USAGE) ON (DATABASES | SCHEMA | CURRENT & FUTURE TABLES) FROM ROLE // 

-- REVOKE ALL PRIVILEGES ON DATABASE EXERCISE_DB FROM ROLE DATA_ANALYST; // Revoke all privileges on the database
-- REVOKE USAGE ON DATABASE EXERCISE_DB FROM ROLE DATA_ANALYST; // Revoke usage on the database

-- REVOKE ALL PRIVILEGES ON SCHEMA EXERCISE_DB.ERRORS FROM ROLE DATA_ANALYST; // Revoke all privileges on the schema
-- << OR >>
-- REVOKE USAGE ON SCHEMA EXERCISE_DB.ERRORS FROM ROLE DATA_ANALYST; // Revoke usage on the schema

-- REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA EXERCISE_DB.ERRORS FROM ROLE DATA_ANALYST; // Revoke all privileges

-- REVOKE ALL PRIVILEGES ON FUTURE TABLES IN SCHEMA EXERCISE_DB.ERRORS FROM ROLE DATA_ANALYST; // Revoke future grants


// BD3 - REVOKE PRIVILAGES ON (ROLE | DATABASES) FROM USER // 

-- REVOKE ROLE DATA_ANALYST FROM USER DA1; // Revoke a role from a user
-- REVOKE ALL PRIVILEGES ON DATABASE EXERCISE_DB FROM USER DA1; // Revoke all privileges on a database for the user 


// BD4 - REVOKE PRIVILAGES ON OBJECTS //

-- REVOKE ALL PRIVILEGES ON DATABASE EXERCISE_DB FROM ROLE DATA_ANALYST; // On the database from roles
-- REVOKE ALL PRIVILEGES ON SCHEMA EXERCISE_DB.FILE_FORMATS FROM ROLE DATA_ANALYST; // On the schema from roles
-- REVOKE ALL PRIVILEGES ON TABLE EXERCISE_DB.EXTERNAL_STAGES.AWS_STAGE1 FROM ROLE DATA_ANALYST; // On a table from roles