USE ROLE SYSADMIN;

CREATE OR REPLACE DATABASE DATA_WAREHOUSING_ANALYSTS;

CREATE OR REPLACE SCHEMA DATA_WAREHOUSING_ANALYSTS.STORAGE_INTEGRATION;
CREATE OR REPLACE SCHEMA DATA_WAREHOUSING_ANALYSTS.FILE_FORMATS;
CREATE OR REPLACE SCHEMA DATA_WAREHOUSING_ANALYSTS.EXTERNAL_STAGE;
CREATE OR REPLACE SCHEMA DATA_WAREHOUSING_ANALYSTS.CLEANED_TABLES;
CREATE OR REPLACE SCHEMA DATA_WAREHOUSING_ANALYSTS.DATA_PIPES;
CREATE OR REPLACE SCHEMA DATA_WAREHOUSING_ANALYSTS.EXTERNAL_TABLES;
CREATE OR REPLACE SCHEMA DATA_WAREHOUSING_ANALYSTS.ERRORS;



CREATE OR REPLACE FILE FORMAT DATA_WAREHOUSING_ANALYSTS.FILE_FORMATS.CSV_FT
    TYPE = CSV
    FIELD_DELIMITER = ','
    SKIP_HEADER = 0
    null_if = ('NULL','null')
    empty_field_as_null = TRUE ;  

CREATE OR REPLACE FILE FORMAT DATA_WAREHOUSING_ANALYSTS.FILE_FORMATS.JSON_FT
    TYPE = JSON ;

CREATE OR REPLACE FILE FORMAT DATA_WAREHOUSING_ANALYSTS.FILE_FORMATS.PARQUET_FT
    TYPE = PARQUET ;



// ERRONEOUS RECORDS
SELECT DISTINCT REJECTS FROM DATA_WAREHOUSING_ANALYSTS.ERRORS.ETF_PRICES_REJECTED;
// ERROR INFORMATION ON METADATA
SELECT DISTINCT file_name, line_number, error_message, column_name, error_category, error_phase
    FROM DATA_WAREHOUSING_ANALYSTS.ERRORS.ETF_PRICES_ERRORS_INFO;
// SINGLE VALUED ERROR DATA
SELECT DISTINCT SPLIT_PART(error_message,'''',2) ERRONEOUS_VALUES, column_name, line_number 
    FROM DATA_WAREHOUSING_ANALYSTS.ERRORS.ETF_PRICES_ERRORS_INFO;

    
//
CREATE OR REPLACE TABLE DATA_WAREHOUSING_ANALYSTS.ERRORS.ETF_PRICES_ERRORED_DATA (
    fund_symbol STRING,
    price_date STRING,
    open STRING,
    high STRING,
    low STRING,
    close STRING,
    adj_close STRING,
    volume STRING,
    error_time TIMESTAMP_NTZ);

    
// 
INSERT INTO DATA_WAREHOUSING_ANALYSTS.ERRORS.ETF_PRICES_ERRORED_DATA
    SELECT 
        SPLIT_PART(t.rejects,',',1) as fund_symbol, 
        SPLIT_PART(t.rejects,',',2) as price_date, 
        SPLIT_PART(t.rejects,',',3) as open, 
        SPLIT_PART(t.rejects,',',4) as high, 
        SPLIT_PART(t.rejects,',',5) as low, 
        SPLIT_PART(t.rejects,',',6) as close,
        SPLIT_PART(t.rejects,',',7) as adj_close,
        SPLIT_PART(t.rejects,',',8) as volume,
        CURRENT_TIMESTAMP AS error_time
    FROM (SELECT DISTINCT REJECTS FROM DATA_WAREHOUSING_ANALYSTS.ERRORS.ETF_PRICES_REJECTED) t; 

SELECT * FROM DATA_WAREHOUSING_ANALYSTS.ERRORS.ETF_PRICES_ERRORED_DATA;
-- TRUNCATE TABLE DATA_WAREHOUSING_ANALYSTS.ERRORS.ETF_PRICES_ERRORED_DATA;